---
- hosts: all
  sudo: yes
  tasks:
    - name: install wget
      apt: name=wget update_cache=yes state=latest
    - name: get docker
      shell: wget -qO- https://get.docker.com/ | sh
      register: docker installed
      ignore_errors: True
    - name: privilage to ubuntu user
      shell: usermod -aG docker ubuntu
      register: privilaged ubuntu
      ignore_errors: True
    - name: install python-pip
      apt: name=python-pip update_cache=yes state=latest
    - name: install docker compose
      shell: pip install docker-compose
      register: installed docker compose
      ignore_errors: True
    - name: creating directory
      file: path=~/wp-docker state=directory
    - name: copying docker compose file 
      copy: src=files/wp_docker.yml dest=~/wp-docker/docker-compose.yml mode=0644
    - name: docker composing
      shell: nohup docker-compose up >/var/log/docker-compose-run.log 2>&1 
      args:
        chdir: somedir/
      register: docker up
